In [1]:
from OpenMatch.models import t5
from transformers import T5Tokenizer
import torch
from OpenMatch.data import DataLoader
from OpenMatch.data.datasets import t5Dataset

In [8]:
dataset=t5Dataset("/home/huxiaomeng/50-q-1-n_msmarco_train.jsonl",tokenizer,template)

In [2]:
model=t5("/home/huxiaomeng/t5v11large",True,False,[1,2,3],[4,5,6],[7,8,9]).to("cuda:6")
ckpt="/data/private/huxiaomeng/promptir/checkpoints/test_v11-large/q1000-n-1/_step-100.bin"
device=torch.device("cuda:6")
model.load_state_dict(torch.load(ckpt,map_location=device))
tokenizer=T5Tokenizer.from_pretrained("/home/huxiaomeng/t5v11large/")
template="Query: <q> Document: <d> Relevant: "
dataset=t5Dataset("/home/huxiaomeng/new/maeningless.jsonl",tokenizer,template)

Some weights of the model checkpoint at /home/huxiaomeng/t5v11large were not used when initializing T5ForConditionalGeneration: ['encoder.block.0.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.0.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.1.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.1.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.2.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.2.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.3.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.3.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.4.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.4.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.5.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.5.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.6.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.6.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.7.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.7.layer.1.DenseReluDense.wi_1.weight', 'encode

tensor([[6136,    1],
        [6136,    1],
        [6136,    1],
        [6136,    1],
        [6136,    1],
        [6136,    1],
        [6136,    1],
        [6136,    1],
        [6136,    1],
        [6136,    1]])


In [9]:
loader = DataLoader(
            dataset=dataset,
            batch_size=10,
            shuffle=False,
            num_workers=0
        )

In [10]:
for i,test_batch  in enumerate(loader):
    batch_score,_=model(
                        input_ids=test_batch['input_ids'].to(device), 
                        attention_mask=test_batch['attention_mask'].to(device),
                        query_ids=test_batch['query_ids'].to(device), 
                        doc_ids=test_batch['doc_ids'].to(device),
                        query_attention_mask=test_batch['query_attention_mask'].to(device),
                        doc_attention_mask=test_batch['doc_attention_mask'].to(device),
                        labels=test_batch['labels'].to(device)
                )

In [13]:
batch_score.softmax(dim=-1)[:,0]

tensor([6.6281e-22, 1.0000e+00, 4.9667e-22, 1.0000e+00, 6.6630e-22, 1.0000e+00,
        5.6396e-22, 1.0000e+00, 3.3981e-22, 1.0000e+00], device='cuda:6',
       grad_fn=<SelectBackward>)

<All keys matched successfully>

tensor([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1]])


In [67]:
 batch_score.softmax(dim=-1)[:, 1].squeeze(-1)

tensor([7.4811e-32, 4.7977e-32, 1.2697e-33, 1.0725e-34, 4.2548e-33, 1.6771e-34,
        5.2594e-31, 2.7186e-33, 3.7752e-33, 5.2866e-34], device='cuda:6',
       grad_fn=<SqueezeBackward1>)

T5Stack(
  (embed_tokens): Embedding(32128, 1024)
  (block): ModuleList(
    (0): T5Block(
      (layer): ModuleList(
        (0): T5LayerSelfAttention(
          (SelfAttention): T5Attention(
            (q): Linear(in_features=1024, out_features=1024, bias=False)
            (k): Linear(in_features=1024, out_features=1024, bias=False)
            (v): Linear(in_features=1024, out_features=1024, bias=False)
            (o): Linear(in_features=1024, out_features=1024, bias=False)
            (relative_attention_bias): Embedding(32, 16)
          )
          (layer_norm): T5LayerNorm()
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (1): T5LayerCrossAttention(
          (EncDecAttention): T5Attention(
            (q): Linear(in_features=1024, out_features=1024, bias=False)
            (k): Linear(in_features=1024, out_features=1024, bias=False)
            (v): Linear(in_features=1024, out_features=1024, bias=False)
            (o): Linear(in_features=1024, out_feat